#Docker compose si on veux uniquement run l'api avec une bdd
services:
  postgres:
    image: postgres:15
    container_name: goodfood_delivery_db_container
    ports:
      - '5435:5435'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 3NvlIk8172Vc<h`:fd
      POSTGRES_DB: goodfood_delivery
      PGPORT: 5435

  mongo: 
    image: mongo:latest 
    container_name: goodfood_delivery_mongodb_container
    ports:
      - '27017:27017' 
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser 
      MONGO_INITDB_ROOT_PASSWORD: testpassword