#Docker compose si on veux uniquement run l'api avec une bdd
services:
  postgres:
    image: postgres:15
    container_name: goodfood_delivery_db_container
    ports:
      - '5433:5433'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 3NvlIk8172Vc<h`:fd
      POSTGRES_DB: goodfood_delivery
      PGPORT: 5433

  mongo: 
    image: mongo:latest 
    container_name: goodfood_delivery_mongodb_container
    ports:
      - '27017:27017' 
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser 
      MONGO_INITDB_ROOT_PASSWORD: j2.kP-tA+hM_zC@xV=nE
    volumes:
      - mongo_data:/data/db 

volumes:
  postgres_data:
  mongo_data: 
